from xhtml2pdf import pisa
from jinja2 import Template
from datetime import datetime
import io

REPORT_TEMPLATE = Template("""
<html>
<head>
<style>
  @page { size: A4; margin: 2cm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a2b4a; }
  h1 { color: #4a7ab5; margin-bottom: 0; }
  .subtitle { color: #7896b8; margin-top: 4px; }
  .score-box { background: #eaf2fb; border-radius: 12px; padding: 20px; margin: 20px 0; text-align: center; }
  .score-box .score { font-size: 48px; font-weight: 700; color: #3d6ea5; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #dbe8f5; }
  th { background: #f2f7fc; color: #3d6ea5; }
  .section-title { color: #3d6ea5; margin-top: 28px; border-bottom: 2px solid #cfe2f5; padding-bottom: 4px; }
  .weak { color: #c0392b; }
  .strong { color: #2e8b57; }
  footer { margin-top: 40px; font-size: 11px; color: #9ab; text-align: center; }
</style>
</head>
<body>
  <h1>NextRound Report Card</h1>
  <div class="subtitle">{{ name }} &middot; Generated {{ date }}</div>

  <div class="score-box">
    <div class="score">{{ overall_percentile }}th</div>
    <div>Overall Percentile</div>
  </div>

  <h2 class="section-title">Topic Breakdown</h2>
  <table>
    <tr><th>Topic</th><th>Attempts</th><th>Avg. Score</th><th>Status</th></tr>
    {% for row in topics %}
    <tr>
      <td>{{ row.topic }}</td>
      <td>{{ row.attempts }}</td>
      <td>{{ row.avg_score }}%</td>
      <td class="{{ 'strong' if row.avg_score >= 60 else 'weak' }}">
        {{ 'Strong' if row.avg_score >= 60 else 'Needs Work' }}
      </td>
    </tr>
    {% endfor %}
  </table>

  <h2 class="section-title">Coding Rounds</h2>
  <table>
    <tr><th>Problem</th><th>Language</th><th>Test Cases Passed</th></tr>
    {% for row in coding %}
    <tr>
      <td>{{ row.problem_title }}</td>
      <td>{{ row.language }}</td>
      <td>{{ row.passed }} / {{ row.total }}</td>
    </tr>
    {% endfor %}
  </table>

  <footer>Generated by NextRound &mdash; AI-Powered Placement Prep Platform</footer>
</body>
</html>
""")


def build_report_pdf(name: str, overall_percentile: int, topics: list[dict], coding: list[dict]) -> bytes:
    html_str = REPORT_TEMPLATE.render(
        name=name,
        date=datetime.utcnow().strftime("%d %b %Y"),
        overall_percentile=overall_percentile,
        topics=topics,
        coding=coding,
    )
    buf = io.BytesIO()
    result = pisa.CreatePDF(src=html_str, dest=buf)
    if result.err:
        raise RuntimeError("Failed to generate the PDF report card.")
    return buf.getvalue()
